name: boost scan

on: push

jobs:
  boost:
    name: boost scan job
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      
      - name: osv-scalibr-sbom scan
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/osv-scalibr-sbom
          api_endpoint: https://api.dev.boostsec.io
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: https://github.com/boostsecurityio/dev-registry.git#BST-19719-scalibr
